# This workflow will test our psql schemas 
name: Postgres

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_USER: postgres
      DB_PASS: postgres
      DB_ADDR: localhost
      DB_PORT: 5432
      DB_NAME: test_db

    steps:
      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run DB schema
        env:
          PGPASSWORD: postgres
        run: |
          psql \
            -h localhost \
            -U postgres \
            -d test_db \
            -v ON_ERROR_STOP=1 \
            -f schemas/db_up.sql

      - name: Run DB seed schema
        env:
          PGPASSWORD: postgres
        run: |
          psql \
            -h localhost \
            -U postgres \
            -d test_db \
            -v ON_ERROR_STOP=1 \
            -f schemas/db_seed.sql

      - name: Run DB down schema
        env:
          PGPASSWORD: postgres
        run: |
          psql \
            -h localhost \
            -U postgres \
            -d test_db \
            -v ON_ERROR_STOP=1 \
            -f schemas/db_down.sql
